@startuml
class RessourceAllocator {
 - {static} INVALID_RESOURCE_ID  : int = -1
 + int allocate(ResourceType resourceType)
 + void free(ResourceType resourceType, int resourceId)
 - void markSpaceSlotFree(int resourceId)
 - void markTimeSlotFree(int resourceId)
 - void markSpaceSlotBusy(int resourceId)
 - int findFreeSpaceSlot()
 - void markTimeSlotBusy(int resourceId)
 -  int findFreeTimeSlot()
}
enum ResourceType
{
    TIME_SLOT,
    SPACE_SLOT
}
ResourceType -- RessourceAllocator
@enduml